In [ ]:
# Task 1 > Create Arrays & View Properties

In [15]:
import numpy as np


arr = np.arange(1, 11)
print(arr)
print("---------------------------------------------------")

arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)
print("---------------------------------------------------")


arr3 = np.random.rand(3, 2, 3)
print(arr3)
print("---------------------------------------------------")


print("1D - Shape:", arr.shape, "Size:", arr.size, "Dtype:", arr.dtype)
print("2D - Shape:", arr2.shape, "Size:", arr2.size, "Dtype:", arr2.dtype)
print("3D - Shape:", arr3.shape, "Size:", arr3.size, "Dtype:", arr3.dtype)
     


[ 1  2  3  4  5  6  7  8  9 10]
---------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------------------------------
[[[0.18224963 0.48916525 0.75691821]
  [0.43941379 0.2171251  0.89082228]]

 [[0.11658513 0.69326258 0.50666303]
  [0.07210537 0.89421195 0.68683867]]

 [[0.87791325 0.82474714 0.99724774]
  [0.2104392  0.70652139 0.01532295]]]
---------------------------------------------------
1D - Shape: (10,) Size: 10 Dtype: int32
2D - Shape: (3, 3) Size: 9 Dtype: int32
3D - Shape: (3, 2, 3) Size: 18 Dtype: float64


In [ ]:
# task 2 > Slice and Reverse Arrays

In [16]:
import numpy as np

data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)

print("First 3:", arr[:3])
print("Alternate:", arr[::2])
print("Reversed:", arr[::-1])


First 3: [10 20 30]
Alternate: [10 30 50 70 90]
Reversed: [90 80 70 60 50 40 30 20 10]


In [ ]:
 # Task 3 > Array Operations

In [25]:
import numpy as np

A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A:", A)
print("B:", B)
print("---------------------------------------------------")

print("Add:", A + B)
print("Sub:", A - B)
print("Mul:", A * B)
print("Div:", A / B)
print("---------------------------------------------------")

print("Dot:", np.dot(A, B))
print("---------------------------------------------------")

print("Mean:", np.mean(A))
print("Median:", np.median(A))
print("Std:", np.std(A))
print("Var:", np.var(A))
print("---------------------------------------------------")

print("Max B:", np.max(B), "at", np.argmax(B))
print("Min B:", np.min(B), "at", np.argmin(B))


A: [ 2  2  7 11 13]
B: [1 7 3 9 5]
---------------------------------------------------
Add: [ 3  9 10 20 18]
Sub: [ 1 -5  4  2  8]
Mul: [ 2 14 21 99 65]
Div: [2.         0.28571429 2.33333333 1.22222222 2.6       ]
---------------------------------------------------
Dot: 201
---------------------------------------------------
Mean: 7.0
Median: 7.0
Std: 4.516635916254486
Var: 20.4
---------------------------------------------------
Max B: 9 at 3
Min B: 1 at 0


In [ ]:
# Task 4 > Reshape and Transpose

In [26]:
import numpy as np

arr = np.arange(1, 13)

# Reshape
arr_2d = arr.reshape(4, 3)
print("2D (4x3):\n", arr_2d)
print("---------------------------------------------------")

# 3D reshaping
arr_3d = arr.reshape(2, 2, 3)
print("3D (2x2x3):\n", arr_3d)
print("---------------------------------------------------")

# Transpose
print("Transposed:\n", arr_2d.T)
print("Shape:", arr_2d.T.shape)


2D (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---------------------------------------------------
3D (2x2x3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---------------------------------------------------
Transposed:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape: (3, 4)


In [ ]:
# Task 5 > replace , filter , count

In [27]:
import numpy as np

arr = np.random.randint(10, 51, 15)

print("Original:", arr)
print("---------------------------------------------------")

print(">20:", arr[arr > 20])
print("---------------------------------------------------")

arr[arr < 20] = 0
print("Replaced:", arr)
print("---------------------------------------------------")

print("Div by 5:", np.sum(arr % 5 == 0))


Original: [27 34 41 21 34 37 48 45 14 30 41 30 25 40 34]
---------------------------------------------------
>20: [27 34 41 21 34 37 48 45 30 41 30 25 40 34]
---------------------------------------------------
Replaced: [27 34 41 21 34 37 48 45  0 30 41 30 25 40 34]
---------------------------------------------------
Div by 5: 6


In [ ]:
# Task 6 > Built-in Functions

In [33]:
import numpy as np

# Linspace
print("Linspace:", np.linspace(0, 1, 10))
print("---------------------------------------------------")

# Identity matrix
print("Identity:\n", np.eye(4))
print("---------------------------------------------------")

arr = np.random.randint(1, 51, 20)
print("org: ",arr)
sorted_arr = np.sort(arr)
print("Sorted:", sorted_arr)
print("Top 5:", sorted_arr[-5:][::-1])


Linspace: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
---------------------------------------------------
Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
---------------------------------------------------
org:  [ 2 21  3 20 42 35 45  8 42 26 42 41 24 36 46 46 37 24 33 48]
Sorted: [ 2  3  8 20 21 24 24 26 33 35 36 37 41 42 42 42 45 46 46 48]
Top 5: [48 46 46 45 42]


In [ ]:
# Task 7 > Matrix

In [39]:
import numpy as np
import time

start = time.time()

A = np.random.rand(10, 10)
B = np.random.rand(10, 10)

# Matrix multiplication
result = np.matmul(A, B)
print("Matrix shape:", result.shape)

# Determinant
det = np.linalg.det(result)
print("Determinant:", det)

# Inverse
inv = np.linalg.inv(result)
print(inv)

end = time.time()



Matrix shape: (10, 10)
Determinant: -0.0001929601867507781
[[-2.20370835e+00 -7.14154939e+00 -1.33819180e+00  7.82785658e-01
  -5.29719276e+00  5.45505002e+00  1.83853049e+00  4.97705749e-02
   8.82274090e+00  1.91652372e+00]
 [ 2.23593348e-02 -7.42180564e+00 -1.41846896e+00  6.15764832e-01
  -5.94578099e+00  3.34425880e+00  4.81088741e+00 -3.26717270e+00
   7.28913804e+00  4.72079870e+00]
 [ 1.22357271e+00  2.70668261e+01  3.19042773e+00 -1.56114015e+00
   2.17179808e+01 -1.86137724e+01 -9.54102976e+00  5.96935338e+00
  -3.07366932e+01 -8.40615357e+00]
 [ 2.40948321e+00 -1.25981679e+01 -2.01089249e+00 -1.14092470e+00
  -1.12336324e+01  9.35612634e+00  6.01169172e+00 -3.50142341e+00
   1.47584410e+01  2.74651165e+00]
 [ 5.67666012e+00  2.89488126e+01  4.37714014e+00 -3.75060081e+00
   2.49656939e+01 -1.81313695e+01 -1.35448981e+01  5.46331510e+00
  -3.20951339e+01 -1.29621780e+01]
 [-4.73953159e+00 -3.16764683e+01 -3.82520402e+00  3.97808729e+00
  -2.49568310e+01  1.86462535e+01  1.463

In [40]:
# Task 8 > Time cal

In [41]:
print("Time:", end - start, "sec")

Time: 0.013076066970825195 sec
